services:
  - type: web
    name: bot-arrampicata
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot-arrampicata.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    pythonVersion: 3.11.9